name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos, windows]
        include:
          - os: macos
            platform: 2
            platform_name: ios
          - os: macos
            platform: 7
            platform_name: iossimulator
          - os: macos
            platform: 8
            platform_name: tvossimulator
          - os: windows
            platform: 2
            platform_name: ios
          - os: windows
            platform: 7
            platform_name: iossimulator
          - os: windows
            platform: 8
            platform_name: tvossimulator

    runs-on: ${{ matrix.os == 'macos' && 'MacStadium' || 'self-hosted' }}

    env:
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}

    steps:
      - name: Cleanup work folders
        shell: bash
        run: |
          echo "Before cleanup:"
          ls -lah ./
          echo "$SUDO_PASSWORD" | sudo -S rm -rf ./* || true
          echo "$SUDO_PASSWORD" | sudo -S rm -rf ./.??* || true
          echo "After cleanup:"
          ls -lah ./

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository submodules
        run: git submodule update --init --recursive
        shell: bash

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          echo "::set-output name=sha::$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^[^\s]*')"
        shell: bash

      - name: Cache gl4es
        uses: actions/cache@v3
        if: false # disabled, keep for reference
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get JRE8
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: success
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-ios-aarch64

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-ios-aarch64

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-ios-aarch64

      - name: Build for ${{ matrix.platform_name }}
        shell: bash
        env:
          RUNNER: 1
          SLIMMED: 1
          PATH: /opt/procursus/bin:/opt/homebrew/bin:$PATH
        run: |
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          else
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          fi

      - name: Upload regular ipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed tipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher.slimmed-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/net.kdt.pojavlauncher.slimmed-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        if: matrix.platform_name == 'ios'
        uses: actions/upload-artifact@v3
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
